# Тут находится специфичная для модуля app конфигурация


user:
  default:
    name: Unknown

limits:
  authorized:
    messages_per_second: 3
    requests_per_second: 5

  unauthorized:
    messages_per_second: 1
    requests_per_second: 1