# Project config file example

admin:
  password: AdMIN_PASS
  username: fivol

#  Максимальное количество запросов в минуту для владельцев pro аккаунтов
limits:
  #  Максимальное количество запросов в минуту для владельцев pro аккаунтов
  requests_pro: 15
  #  Максимальное количество запросов в минуту для владельцев обычного аккаунта
  requests_base: 3

bot:
  id: 74820475
